%YAML:1.0
​
#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
File.version: "1.0"
​
Camera.type: "PinHole"
​
# Camera calibration and distortion parameters (OpenCV) 
Camera1.fx: 1170.19
Camera1.fy: 1170.19
Camera1.cx: 647.75
Camera1.cy: 483.75
​
Camera1.k1: 0.0
Camera1.k2: 0.0
Camera1.p1: 0.0
Camera1.p2: 0.0
Camera1.k3: 0.0
​
Camera.width: 1296
Camera.height: 968
​
Camera.newWidth: 640
Camera.newHeight: 480
​
# Camera frames per second 
Camera.fps: 30
​
# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1
​
# Close/Far threshold. Baseline times.
Stereo.ThDepth: 40.0
Stereo.b: 0.089768
​
# Depth map values factor
RGBD.DepthMapFactor: 1000.0 # 1.0 for ROS_bag
​
System.EmulateCamera: 1
System.skipGBA: 0
System.skipLBA: 0
​
#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------
​
# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 1500
​
# ORB Extractor: Scale factor between levels in the scale pyramid 	
ORBextractor.scaleFactor: 1.2
​
# ORB Extractor: Number of levels in the scale pyramid	
ORBextractor.nLevels: 8
​
# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast			
ORBextractor.iniThFAST: 20 #10 #20
ORBextractor.minThFAST: 7 #3 #7
​
#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1.0
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2.0
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3.0
Viewer.ViewpointX: 0.0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -1.8
Viewer.ViewpointF: 500.0